[project]
name = "project-repo-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fastmcp>=3.1.1",
    "langchain>=1.2.12",
    "langgraph>=1.1.2",
    "mcp>=1.26.0",
    "pre-commit>=4.5.1",
    "requests>=2.32.5",
    "wikipedia>=1.4.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
